### ISSUE TITLE
Monaco font cannot be applied on VS code

### ISSUE THREAD

**Issue by Develop-CharlieLee** [taodongl/monaco.ttf#4]
I added `"editor.fontFamily": "Monaco"` on vs code settings file, but it won't be added. I successed applying on Intellij IDEA, however, it won't apply on VS code.

**Comment by Develop-CharlieLee** [comment]
Just successed by wrapping Monaco by apostrophes. i.e. `"editor.fontFamily": "'Monaco'"`

**Comment by osseigh** [comment]
I tried this `"editor.fontFamily": "'Monaco'"` and its still not working

**Comment by bahram-hodjaev** [comment]
Hi, @osseigh try this `"editor.fontFamily": "Monaco, Consolas, 'Courier New', monospace"`

**Comment by ZhiyuanChen** [comment]
> I tried this `"editor.fontFamily": "'Monaco'"` and its still not working

Have you add `"editor.fontLigatures": true,` to settings.json?

**Comment by akawajid** [comment]
I guess **Monaco** font should be installed in your system. I had this issue but resolved it successfully after installing the font in Windows.
